### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by bsideup** [forge/furnace-guice#1]
Hi @gastaldi !

Could you please release this one? 

Thanks!

**Comment by gastaldi** [comment]
Hi @bsideup 
I'll release an Alpha version asap. Thanks

**Comment by bsideup** [comment]
Great! Thank you :)

**Comment by gastaldi** [comment]
1.0.0.Alpha1 released, enjoy! :dancers:

**Comment by bsideup** [comment]
Wow! That was fast! 🎉 👍 Thanks!
